export const ActionTypes = {
    SET_EPISODES: "SET_EPISODES",
    SET_CHARACTERS: "SET_CHARACTERS",
    SELECT_EPISODE: "SELECT_EPISODE",

    ADD_FAVOURITE: "ADD_FAVOURITE",
    DELETE_FAVOURITE: "DELETE_FAVOURITE",
    ADD_LIKE: "ADD_LIKE",
    DELETE_LIKE: "DELETE_LIKE",
    FILTERBY_CHARACTER: "FILTERBY_CHARACTER",
    SEARCH_EPISODE: "SEARCH_EPISODE"
}